version: "3.7"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "8080:3333"
