version: "3.7"

services:
  mongodb:
    image: mongo:3.6.10
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - default
    volumes: 
      - ./.volumes/db:/data
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "8080:3333"
    depends_on:
      - mongodb
    networks:
      - default
networks:
  default:
    driver: bridge